Lint

diff --git a/.local/bin/grimblast b/.local/bin/grimblast
--- a/.local/bin/grimblast
+++ b/.local/bin/grimblast
@@ -1,46 +1,23 @@
 #!/usr/bin/env bash
-## Grimblast: a helper for screenshots within hyprland
-## Requirements:
-##  - `grim`: screenshot utility for wayland
-##  - `slurp`: to select an area
-##  - `hyprctl`: to read properties of current window
-##  - `wl-copy`: clipboard utility
-##  - `jq`: json utility to parse hyprctl output
-##  - `notify-send`: to show notifications
-## Those are needed to be installed, if unsure, run `grimblast check`
-##
-## See `man 1 grimblast` or `grimblast usage` for further details.
+
+# Based on Grimblast, which is base on grimshot
 
 ## Author: Misterio (https://github.com/misterio77)
-
-## This tool is based on grimshot, with swaymsg commands replaced by their
-## hyprctl equivalents.
 ## https://github.com/swaywm/sway/blob/master/contrib/grimshot
 
-# Later modifications by Mario D'Andrea <https://github.com/ormai>
-# - remove slurp border
-# - date format is %Y_%m_%d-%H_%M_%S
-# - readapt to Sway
+# Later modifications by Mario D'Andrea <https://ormai.dev>
+
+for command in grim swaymsg jq slurp wl-copy notify-send; do
+  if ! command -v "$command" >/dev/null 2>&1; then
+    echo "$command: not found"
+  fi
+done
 
 getTargetDirectory() {
   test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" &&
     . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
 
   echo "${XDG_SCREENSHOTS_DIR:-${XDG_PICTURES_DIR:-$HOME}}"
-}
-
-tmp_editor_directory() {
-  echo "/tmp"
-}
-
-#Detect if $GRIMBLAST_EDITOR env exist
-env_editor_confirm() {
-  if [ -n "$GRIMBLAST_EDITOR" ]; then
-    echo "GRIMBLAST_EDITOR is set. Continuing..."
-  else
-    echo "GRIMBLAST_EDITOR is not set. Defaulting to gimp"
-    GRIMBLAST_EDITOR=gimp
-  fi
 }
 
 NOTIFY=no
@@ -66,21 +43,17 @@ done
 
 ACTION=${1:-usage}
 SUBJECT=${2:-screen}
-FILE=${3:-$(getTargetDirectory)/$(date +%Y_%m_%d-%H_%M_%S).png}
-FILE_EDITOR=${3:-$(tmp_editor_directory)/$(date +%Y_%m_%d-%H_%M_%S).png}
+FILE=${3:-$(getTargetDirectory)/$(date --iso-8601=seconds).png}
 
-if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "edit" ] && [ "$ACTION" != "copysave" ] && [ "$ACTION" != "check" ]; then
+if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "copysave" ]; then
   echo "Usage:"
-  echo "  grimblast [--notify] [--cursor] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
-  echo "  grimblast check"
+  echo "  grimblast [--notify] [--cursor] (copy|save|copysave) [active|screen|output|area] [FILE|-]"
   echo "  grimblast usage"
   echo ""
   echo "Commands:"
   echo "  copy: Copy the screenshot data into the clipboard."
   echo "  save: Save the screenshot to a regular file or '-' to pipe to STDOUT."
   echo "  copysave: Combine the previous 2 options."
-  echo "  edit: Open screenshot in the image editor of your choice (default is gimp). See man page for info."
-  echo "  check: Verify if required tools are installed and exit."
   echo "  usage: Show this message and exit."
   echo ""
   echo "Targets:"
@@ -92,7 +65,7 @@ if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "edit" ]
 fi
 
 notify() {
-  notify-send -t 3000 -a grimblast "$@"
+  notify-send --urgency=low --expire-time=3000 --app-name=grimblast "$@"
 }
 
 notifyOk() {
@@ -117,15 +90,6 @@ die() {
   exit 2
 }
 
-check() {
-  COMMAND=$1
-  if command -v "$COMMAND" >/dev/null 2>&1; then
-    RESULT="OK"
-  else
-    RESULT="NOT FOUND"
-  fi
-  echo "   $COMMAND: $RESULT"
-}
 
 takeScreenshot() {
   FILE=$1
@@ -140,16 +104,7 @@ takeScreenshot() {
   fi
 }
 
-if [ "$ACTION" = "check" ]; then
-  echo "Checking if required tools are installed. If something is missing, install it to your system and make it available in PATH..."
-  check grim
-  check slurp
-  check hyprctl
-  check wl-copy
-  check jq
-  check notify-send
-  exit
-elif [ "$SUBJECT" = "active" ]; then
+if [ "$SUBJECT" = "active" ]; then
   FOCUSED=$(swaymsg -t get_tree | jq -r 'recurse(.nodes[]?, .floating_nodes[]?) | select(.focused)')
   GEOM=$(echo "$FOCUSED" | jq -r '.rect | "\(.x),\(.y) \(.width)x\(.height)"')
   APP_ID=$(echo "$FOCUSED" | jq -r '.app_id')
@@ -168,8 +123,6 @@ elif [ "$SUBJECT" = "area" ]; then
     exit 1
   fi
   WHAT="Area"
-elif [ "$SUBJECT" = "window" ]; then
-  die "Subject 'window' is now included in 'area'"
 else
   die "Unknown subject to take a screen shot from" "$SUBJECT"
 fi
@@ -186,21 +139,10 @@ elif [ "$ACTION" = "save" ]; then
   else
     notifyError "Error taking screenshot with grim"
   fi
-elif [ "$ACTION" = "edit" ]; then
-  env_editor_confirm
-  if takeScreenshot "$FILE_EDITOR" "$GEOM" "$OUTPUT"; then
-    TITLE="Screenshot of $SUBJECT"
-    MESSAGE="Open screenshot in image editor"
-    notifyOk "$TITLE" "$MESSAGE" -i "$FILE_EDITOR"
-    $GRIMBLAST_EDITOR "$FILE_EDITOR"
-    echo "$FILE_EDITOR"
-  else
-    notifyError "Error taking screenshot"
-  fi
 else
   if [ "$ACTION" = "copysave" ]; then
     takeScreenshot - "$GEOM" "$OUTPUT" | tee "$FILE" | wl-copy --type image/png || die "Clipboard error"
-    notifyOk "$WHAT copied to buffer and saved to $FILE" -i "$FILE"
+    notifyOk "$WHAT copied to clipboard and saved to $FILE" -i "$FILE"
     echo "$FILE"
   else
     notifyError "Error taking screenshot with grim"
